#%RAML 1.0 Library
uses:
  FHIR_commons: /exchange_modules/org.mule.examples/fhir-r4-commons-library/1.0.0/fhir-r4-commons-library.raml

types:
  procedureperformedDateTime:
    properties:
      performedDateTime:
        description: When the procedure was performed
        type: FHIR_commons.dateTime
  procedureperformedPeriod:
    properties:
      performedPeriod:
        description: When the procedure was performed
        type: FHIR_commons.Period
  procedureperformedString:
    properties:
      performedString:
        description: When the procedure was performed
        type: string
  procedureperformedAge:
    properties:
      performedAge:
        description: When the procedure was performed
        type: FHIR_commons.Age
  procedureperformedRange:
    properties:
      performedRange:
        description: When the procedure was performed
        type: FHIR_commons.Range


  Procedure:
    type: FHIR_commons.DomainResource
    properties:
      identifier?:
        type: FHIR_commons.Identifier[]
        description: External Identifiers for this procedure
      instantiatesCanonical?:
        type: FHIR_commons.canonical[]
        description: Instantiates FHIR protocol or definition
      instantiatesUri?:
        type: FHIR_commons.uri[]
        description: Instantiates external protocol or definition
      partOf?:
        type: FHIR_commons.Reference[]
        description: Part of referenced event
      basedOn?:
        type: FHIR_commons.Reference[]
        description: A request for this procedure
      status:
        type: FHIR_commons.code
        description: preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown
        enum: [preparation , in-progress , not-done , on-hold , stopped , completed , entered-in-error , unknown]
      statusReason?: 
        type: FHIR_commons.CodeableConcept
        description: Reason for current status
      category?:
        description: Classification of the procedure
        type: FHIR_commons.CodeableConcept
      code?:
        type: FHIR_commons.CodeableConcept
        description: Identification of the procedure
      subject:
        type: FHIR_commons.Reference
        description: Who the procedure was performed on
      encounter?:
        type: FHIR_commons.Reference
        description: Encounter created as part of      
      performed?:
        type: procedureperformedDateTime | procedureperformedPeriod | procedureperformedString | procedureperformedAge | procedureperformedRange
        description: When the procedure was performed
      
      recorder?:
        type: FHIR_commons.Reference
        description: Who recorded the procedure
      asserter?:
        type: FHIR_commons.Reference
        description: Person who asserts this procedure
      performer?:
        type: array
        description: The people who performed the procedure
        items: 
          type: FHIR_commons.BackboneElement
          properties:
            function?: 
              type: FHIR_commons.CodeableConcept
              description: Type of performance
            actor: 
              type: FHIR_commons.Reference
              description: 
            onBehalfOf?:
              type: FHIR_commons.Reference
              description: Organization the device or practitioner was acting for 
      location?:
        type: FHIR_commons.Reference
        description: Where the procedure happened
      reasonCode?:
        description: Coded reason procedure performed
        type: FHIR_commons.CodeableConcept[]
      reasonReference?:
        type: FHIR_commons.Reference[]
        description: The justification that the procedure was performed
      bodySite?:
        type: FHIR_commons.CodeableConcept[]
        description: Target body sites
      report?:
        type: FHIR_commons.Reference[]
        description: Any report resulting from the procedure
      outcome?:
        type: FHIR_commons.CodeableConcept
        description: The result of procedure
      complication?:
        description: Complication following the procedure
        type: FHIR_commons.CodeableConcept[]
      complicationDetail?:
        type: FHIR_commons.Reference[]
        description: A condition that is a result of the procedure
      followUp?:
        type: FHIR_commons.CodeableConcept[]
        description: Instructions for follow up
      note?:
        type: FHIR_commons.Annotation[]
        description: Additional information about the procedure
      focalDevice?:
        type: array
        description: Manipulated, implanted, or removed device
        items:
          type: FHIR_commons.BackboneElement
          properties:
            action?:
              type: FHIR_commons.CodeableConcept
              description: Kind of change to device 
            manipulated: 
              type: FHIR_commons.Reference
              description: Device that was changed      
      usedReference?:
        type: FHIR_commons.Reference[]
        description: Items used during procedure
      usedCode?:
        type: FHIR_commons.CodeableConcept[]
        description: Coded items used during the procedure 

  ProcedureEntry:
    type: FHIR_commons.Entry
    properties:
      resource: Procedure

  ProcedureBundle:
    type: FHIR_commons.Bundle
    properties:
      entry?: ProcedureEntry[]