#%RAML 1.0 DataType
type: object
description: Project lock enables editing mode for the user that locks the project, and readonly mode for all other users.
properties:
  locked:
    type: boolean
    description: True when the user has the lock, otherwise false.
    example: true
  name:
    type: string
    required: false
    description: Name of the user
    example: 'demo-username'