#%RAML 1.0 DataType
type: object
properties:
  main:
    type: string
    description: Main file of the project to be published
    example: 'api.raml'
  apiVersion:
    type: string
    description: Version of the API, which corresponds to the specification's version property
    example: '1.0.0'
  version:
    type: string
    description: Version of the Exchange Asset to be published
    example: '1.0.0'
  assetId:
    type: string
    description: Exchange Asset ID
    example: 'publish-project-doc'
  groupId:
    type: string
    example: 'gid1234'
    description: Business group ID to which the project is going to be published
  classifier:
    type: string
    enum: ['oas', 'raml', 'raml-fragment']
    description: Classifier of the project being published which is related to the asset's language.
    example: "oas"