#%RAML 1.0 DataType
type: string
description: UUID (Universally Unique Identifier)
pattern: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
example: 6a2f41a3-c54c-fce8-32d2-0324e1c32e22