#%RAML 1.0 Library
uses:
  FHIR_commons: /exchange_modules/org.mule.examples/fhir-r4-commons-library/1.0.0/fhir-r4-commons-library.raml

types:
  Location:
    type: FHIR_commons.DomainResource
    description: |
      Details and position information for a physical place
      Elements defined in Ancestors: id, meta, implicitRules, language, text, contained, extension, modifierExtension
    properties:
      identifier?:
        description: Unique code or number identifying the location to its users
        type: FHIR_commons.Identifier[]
      status?:
        description: active | suspended | inactive
        type: FHIR_commons.code
        enum: [active, suspended, inactive]
      operationStatus?:
        description: The operational status of the location (typically only for a bed/room)
        type: FHIR_commons.Coding    
      name?:
        description: Name of the location as used by humans
        type: string
      alias?:
        description: A list of alternate names that the location is known as, or was known as, in the past
        type: string[]
      description?:
        description: Additional details about the location that could be displayed as further information to identify the location beyond its name
        type: string
      mode?:
        description: instance | kind
        type: FHIR_commons.code
        enum: [instance, kind]
      type?:
        description: Type of function performed
        type: FHIR_commons.CodeableConcept[]
      telecom?:
        description: Contact details of the location
        type: FHIR_commons.ContactPoint[]
      address?:
        description: Physical location
        type: FHIR_commons.Address
      physicalType?:
        description: Physical form of the location
        type: FHIR_commons.CodeableConcept
      position?:
        type: FHIR_commons.BackboneElement
        description: The absolute geographic location
        properties:
          longitude: 
            type: FHIR_commons.decimal
            description: Longitude with WGS84 datum
          latitude:
            type: FHIR_commons.decimal
            description: Latitude with WGS84 datum
          altitude?:
            type: FHIR_commons.decimal
            description: Altitude with WGS84 datum
      managingOrganization?:
        type: FHIR_commons.Reference
        description: Organization responsible for provisioning and upkeep 
      partOf?:
        type: FHIR_commons.Reference
        description: Another Location this one is physically a part of    
      
      hoursOfOperation?:
        description: |
          What days/times during a week is this location usually open
        type: array
        items:
          type: FHIR_commons.BackboneElement
          properties:
            daysoOfWeek?:
              description: mon | tue | wed | thu | fri | sat | sun
              type: FHIR_commons.code[]
            allDay:
              description: The Location is open all day
              type: boolean
            openingTime?:
              description: |
                Time that the Location opens
              type: FHIR_commons.time
            closingTime?:
              description: Time that the Location closes
              type: FHIR_commons.time
      availabilityExceptions?:
        description: Description of availability exceptions
        type: string
      endpoint?:
        description: Technical endpoints providing access to services operated for the location
        type: FHIR_commons.Reference[]


  LocationEntry:
    type: FHIR_commons.Entry
    properties:
      resource: Location

  LocationBundle:
    type: FHIR_commons.Bundle
    properties:
      entry?: LocationEntry[]
