#%RAML 1.0 Library
usage: Extensions to the CIM Market subject area types

uses:
  PartyExtTypes: libraries/PartyExtTypeLibrary.raml

types:
  # Extended Party types
  AccountExt:
    type: PartyExtTypes.AccountExt
    example: !include ./examples/AccountExtExample.json
