#%RAML 1.0 Library
usage: This library provides extended types for the Sales Order group

uses:
  FinanceTypes: ../exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/accelerator-cim-finance-library.raml
  MarketTypes: ../exchange_modules/org.mule.examples/accelerator-cim-market-library/1.2.0/accelerator-cim-market-library.raml
  ProduceTypes: ../exchange_modules/org.mule.examples/accelerator-cim-produce-library/1.2.0/accelerator-cim-produce-library.raml
  SellTypes: ../exchange_modules/org.mule.examples/accelerator-cim-sell-library/1.2.0/accelerator-cim-sell-library.raml

types:
  OrderDeliveryMethodExt:
    type: SellTypes.OrderDeliveryMethod
    properties:
      productExt?: ProduceTypes.Product[]
  SalesOrderExt:
    type: SellTypes.SalesOrder
    properties:
      billToEmailExt?: MarketTypes.ContactPointEmail[]
      shipToEmailExt?: MarketTypes.ContactPointEmail[]
      paymentMethodExt?: FinanceTypes.PaymentMethod[]
      billToAccountExt?: MarketTypes.Account[]
      sellerExt?: MarketTypes.Seller[]
      billToAddressExt?: MarketTypes.ContactPointAddress[]
      shipToAddressExt?: MarketTypes.ContactPointAddress[]
      billToContactExt?: MarketTypes.AccountContact[]
      internalBusinessUnitExt?: MarketTypes.InternalBusinessUnit[]
      billToPhoneNumberExt?: MarketTypes.ContactPointPhone[]
      soldToCustomerExt?: MarketTypes.Customer[]
      shipToContactExt?: MarketTypes.AccountContact[]
  SalesOrderDeliveryGroupExt:
    type: SellTypes.SalesOrderDeliveryGroup
    properties:
      contactPointAddressExt?: MarketTypes.ContactPointAddress[]
      accountContactExt?: MarketTypes.AccountContact[]
  SalesOrderPaymentSummaryExt:
    type: SellTypes.SalesOrderPaymentSummary
    properties:
      paymentMethodExt?: FinanceTypes.PaymentMethod[]
  SalesOrderProductExt:
    type: SellTypes.SalesOrderProduct
    properties:
      shippingPhoneExt?: MarketTypes.ContactPointPhone[]
      productExt?: ProduceTypes.Product[]
      shippingAddressExt?: MarketTypes.ContactPointAddress[]
      shipingEmailExt?: MarketTypes.ContactPointEmail[]
      sellerAccountExt?: MarketTypes.Account[]
