#%RAML 1.0 Library
usage: Extensions to the CIM Fulfill subject area types

uses:
  ShipmentExtTypes: libraries/ShipmentExtTypeLibrary.raml

types:
  # Extended Shipment types
  ShipmentExt:
    type: ShipmentExtTypes.ShipmentExt
    example: !include ./examples/ShipmentExtExample.json
  ShipmentProductExt:
    type: ShipmentExtTypes.ShipmentProductExt
    example: !include ./examples/ShipmentProductExtExample.json
  ShippingMethodExt:
    type: ShipmentExtTypes.ShippingMethodExt
    example: !include ./examples/ShippingMethodExtExample.json
