#%RAML 1.0 Library
usage: Types representing a method of paying for a product or service

uses:
  GlobalTypes: ../exchange_modules/org.mule.examples/accelerator-cim-global-library/1.1.2/accelerator-cim-global-library.raml

types:
  Coupon:
    type: PaymentMethod
    properties:
      # Accelerators: changed to string for Party.id reference
      manufacturer?:
        items: string
      primaryScanCodeLabel?:
        type: string
      isReturnCoupon?:
        type: boolean | nil
      expirationDate?:
        type: date-only | nil
      secondaryScanCodeLabel?:
        type: string
      scanCode?:
        type: string
      couponCode?:
        type: string
      returnCouponReason?:
        type: string
      discountAmount?:
        type: integer | nil
      isValid?:
        type: boolean | nil
      couponStatus?:
        type: string
      discountPercentage?:
        type: integer | nil
      couponCount?:
        type: integer | nil
  CreditTender:
    type: PaymentMethod
    properties:
      # Accelerators: changed to string for Account.id reference
      account?:
        items: string
  PaymentCard:
    type: PaymentMethod
    properties:
      name:
        type: string
      # Accelerators: made property optional
      creditCardExpired?:
        type: boolean | nil
      cardToken:
        type: string
      issueNumber:
        type: string
      billToCity?:
        type: string
      maskedNumber:
        type: string
      companyName?:
        type: string
      cardHolderName:
        type: string
      numberLastDigits:
        type: string
      paymentCardType:
        type: string
      derivedCardTypeCode?:
        type: string
      billToFirstName?:
        type: string
      billToStreet?:
        type: string
      expirationYear:
        type: string
      billToStreet2?:
        type: string
      expirationMonth:
        type: string
      billToLastName?:
        type: string
  PaymentMethod:
    properties:
      id:
        type: string | nil
      # Accelerators: added string union for PaymentMethodType.id reference
      # Accelerators: made property optional
      paymentMethodType?:
        items: string | PaymentMethodType
      paymentMethodStatus:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentMethodType:
    properties:
      id:
        type: string | nil
      name?:
        type: string
      typeDescription?:
        type: string
      mediaType?:
        type: string
      maxPerPeriodAmount?:
        type: integer | nil
      typeRequiredIdentification?:
        type: string
      useMinimumAgeYear?:
        type: integer | nil
      maxTransactionAmount?:
        type: integer | nil
      maxPerPeriodTransactionCount?:
        type: integer | nil
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
