#%RAML 1.0 Library
usage: Types representing payment interactions and processing

uses:
  GlobalTypes: ../exchange_modules/org.mule.examples/accelerator-cim-global-library/1.1.2/accelerator-cim-global-library.raml
  PaymentMethodTypes: PaymentMethodTypeLibrary.raml

types:
  CapturePayment:
    type: Payment
    properties:
      capturePaymentType:
        type: string
      handlingFeeAmount?:
        type: integer | nil
      # Accelerators: added string union for PaymentAuthorization.id reference
      # Accelerators: made property optional
      paymentAuthorization?:
        items: string | PaymentAuthorization
      isFinalCapture?:
        type: boolean | nil
  Payment:
    properties:
      id:
        type: string | nil
      # Accelerators: made optional due to weaker constraints originally found in child types
      name?:
        type: string
      paymentStatus:
        type: string
      authorizationProcessingMode:
        type: string
      # Accelerators: changed to string for Account.id reference
      account?:
        items: string
      # Accelerators: changed to string for SalesOrderPaymentSummary.id reference
      # Accelerators: made property optional
      salesOrderPaymentSummary?:
        items: string
      # Accelerators: added string union for PaymentGatewayResultCode.id reference
      # Accelerators: made property optional
      latestGatewayResultCode?:
        items: string | PaymentGatewayResultCode
      iPAddress?:
        type: string
      # Accelerators: made property optional
      commentText?:
        type: string
      paymentNumber:
        type: string
      # Accelerators: added string union for PaymentGroup.id reference
      # Accelerators: made property optional
      paymentGroup?:
        items: string | PaymentGroup
      paymentAmount:
        type: integer
      # Accelerators: made property optional
      latestGatewayInternalResult?:
        type: string
      customerEmailAddress?:
        type: string
      # Accelerators: made property optional
      latestGatewayReferenceNumber?:
        type: string
      # Accelerators: added string union for PaymentMethod.id reference
      # Accelerators: made property optional
      paymentMethod?:
        items: string | PaymentMethodTypes.PaymentMethod
      # Accelerators: made property optional
      latestGatewayDate?:
        type: date-only | nil
      # Accelerators: made property optional
      balanceAmount?:
        type: integer | nil
      paymentType:
        type: string
      # Accelerators: added string union for PaymentGateway.id reference
      # Accelerators: made property optional
      paymentGateway?:
        items: string | PaymentGateway
      customerPhoneNumber?:
        type: string
      latestPaymentGatewayMessageText?:
        type: string
      paymentEffectiveDate:
        type: date-only
      # Accelerators: added string union for PaymentTreatment.id reference
      # Accelerators: made property optional
      paymentTreatment?:
        items: string | PaymentTreatment
      # Accelerators: made property optional
      externalCreatedDate?:
        type: date-only | nil
      # Accelerators: changed to string for Party.id reference
      # Accelerators: made property optional
      internalBusinessUnit?:
        items: string
      # Accelerators: made property optional
      paymentCancellationDate?:
        type: date-only | nil
      macAddress?:
        type: string
      # Accelerators: made property optional
      totalAppliedAmount?:
        type: integer | nil
      # Accelerators: made property optional
      netAppliedAmount?:
        type: integer | nil
      # Accelerators: made property optional
      totalUnappliedAmount?:
        type: integer | nil
      # Accelerators: made property optional
      latestGatewayInternalReferenceNumber?:
        type: string
      # Accelerators: added support for external identifiers
      externalIds?: 
        items: string | GlobalTypes.ExternalId
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentAllocation:
    properties:
      id:
        type: string | nil
      externalCreatedDate:
        type: date-only
      # Accelerators: changed to string for PaymentAllocation.id reference
      # Accelerators: made property optional
      relatedPaymentAllocation?:
        items: string
      paymentAllocationName?:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentApplication:
    properties:
      id:
        type: string | nil
      # Accelerators: made optional due to weaker constraints originally found in child types
      name?:
        type: string
      effectiveDate:
        type: date-only
      paymentApplicationType:
        type: string
      commentText?:
        type: string
      hasBeenUnapplied?:
        type: boolean | nil
      # Accelerators: added string union for Payment.id reference
      # Accelerators: made property optional
      payment?:
        items: string | Payment
      appliedAmount:
        type: integer
      # Accelerators: made property optional
      paymentBalanceAmount?:
        type: integer | nil
      appliedDate:
        type: date-only
      # Accelerators: made property optional
      externalCreatedDate?:
        type: date-only | nil
      # Accelerators: made property optional
      unappliedDate?:
        type: date-only | nil
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentAuthorization:
    properties:
      id:
        type: string | nil
      paymentGatewayReferenceNumber:
        type: string
      # Accelerators: changed to string for SalesOrderPaymentSummary.id reference
      # Accelerators: made property optional
      salesOrderPaymentSummary?:
        items: string
      iPAddress?:
        type: string
      totalPaymentCaptureAmount:
        type: integer
      paymentAuthorizationProcessingMode:
        type: string
      authorizationAmount:
        type: integer
      expirationDate:
        type: date-only
      # Accelerators: added string union for PaymentGroup.id reference
      # Accelerators: made property optional
      paymentGroup?:
        items: string | PaymentGroup
      # Accelerators: made property optional
      paymentGatewayInternalReferenceNumber?:
        type: string
      # Accelerators: made property optional
      gatewayReferenceDetailsText?:
        type: string
      # Accelerators: made property optional
      totalAuthorizationReversalAmount?:
        type: integer | nil
      # Accelerators: added string union for PaymentGateway.id reference
      # Accelerators: made property optional
      paymentGateway?:
        items: string | PaymentGateway
      # Accelerators: added string union for PaymentGatewayResultCode.id reference
      paymentGatewayResult:
        items: string | PaymentGatewayResultCode
      paymentAuthorizationCommentText?:
        type: string
      # Accelerators: made property optional
      externalCreatedDate?:
        type: date-only | nil
      paymentAuthorizationNumber:
        type: string
      requestDate:
        type: time-only
      # Accelerators: made property optional
      availableBalanceAmount?:
        type: integer | nil
      # Accelerators: added string union for PaymentMethod.id reference
      # Accelerators: made property optional
      paymentMethodID?:
        items: string | PaymentMethodTypes.PaymentMethod
      gatewayResultCodeDescription?:
        type: string
      macAddress?:
        type: string
      gatewayAuthorizationCode:
        type: string
      paymentGatewayDate:
        type: time-only
      paymentAuthorizationStatus:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentAuthorizationReversal:
    properties:
      id:
        type: string | nil
      paymentGatewayReferenceNumber:
        type: string
      authorizationReversalAmount:
        type: integer
      # Accelerators: added string union for Payment.id reference
      capturePayment?:
        items: string | Payment
      customerAuthorizationReversalPhone?:
        type: string
      iPAddress?:
        type: string
      paymentAuthorizationReversalStatus:
        type: string
      paymentAuthorizationProcessingMode:
        type: string
      # Accelerators: made property optional
      paymentGatewayInternalReferenceNumber?:
        type: string
      paymentAuthorizationReversalName?:
        type: string
      # Accelerators: added string union for PaymentGatewayResultCode.id reference
      paymentGatewayResult:
        items: string | PaymentGatewayResultCode
      # Accelerators: added string union for PaymentAuthorization.id reference
      # Accelerators: made property optional
      paymentAuthorization?:
        items: string | PaymentAuthorization
      # Accelerators: made property optional
      externalCreatedDate?:
        type: date-only | nil
      requestDate:
        type: time-only
      paymentAuthorizationReversalCommentText?:
        type: string
      macAddress?:
        type: string
      customerAuthorizationReversalEmail?:
        type: string
      paymentGatewayDate:
        type: time-only
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentCreditMemoAllocation:
    type: PaymentAllocation
    properties:
      name?:
        type: string
      appliedAmount:
        type: integer
  PaymentCreditMemoApplication:
    type: PaymentApplication
    properties: {}
  PaymentGateway:
    properties:
      id:
        type: string | nil
      name:
        type: string
      paymentGatewayStatus:
        type: string
      paymentGatewayCommentText?:
        type: string
      # Accelerators: added string union for PaymentGatewayProvider.id reference
      # Accelerators: made property optional
      paymentGatewayProvider?:
        items: string | PaymentGatewayProvider
      systemCredential?:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentGatewayAuthorizationLog:
    type: PaymentGatewayInteractionLog
    properties:
      # Accelerators: added string union for PaymentAuthorization.id reference
      # Accelerators: made property optional
      paymentAuthorization?:
        items: string | PaymentAuthorization
  PaymentGatewayAuthReversalLog:
    type: PaymentGatewayInteractionLog
    properties:
      # Accelerators: added string union for PaymentAuthorizationReversal.id reference
      paymentAuthorizationReversal?:
        items: string | PaymentAuthorizationReversal
  PaymentGatewayInteractionLog:
    properties:
      id:
        type: string | nil
      name?:
        type: string
      # Accelerators: added string union for PaymentGatewayInteractionType.id reference
      paymentGatewayInteractionType:
        items: string | PaymentGatewayInteractionType
      # Accelerators: made property optional
      paymentGatewayReferenceNumber?:
        type: string
      paymentGatewayMessageText?:
        type: string
      # Accelerators: made property optional
      paymentGatewayAuthorizationCode?:
        type: string
      # Accelerators: made property optional
      internalResultCode?:
        type: string
      # Accelerators: made property optional
      paymentGatewayAVSCode?:
        type: string
      internalReferenceNumber:
        type: string
      # Accelerators: added string union for PaymentGatewayResultCode.id reference
      paymentGatewayResult:
        items: string | PaymentGatewayResultCode
      paymentGatewayInteractionLogName:
        type: string
      paymentGatewayInteractionStatus:
        type: string
      paymentGatewayDate:
        type: date-only
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentGatewayInteractionType:
    properties:
      id:
        type: string | nil
      name:
        type: string
      description:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentGatewayPaymentLog:
    type: PaymentGatewayInteractionLog
    properties:
      # Accelerators: added string union for Payment.id reference
      # Accelerators: made property optional
      payment?:
        items: string | Payment
  PaymentGatewayProvider:
    properties:
      id:
        type: string | nil
      # Accelerators: made property optional
      apexAdapterClassName?:
        type: string
      paymentGatewayProviderCommentText?:
        type: string
      paymentGatewayProviderName:
        type: string
      # Accelerators: made property optional
      developerName?:
        type: string
      # Accelerators: made property optional
      namespacePrefixText?:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentGatewayResultCode:
    properties:
      id:
        type: string | nil
      name:
        type: string
      description:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentGroup:
    properties:
      id:
        type: string | nil
      totalReversalAmount:
        type: integer
      totalAuthorizationAmount:
        type: integer
      totalPaymentAmount:
        type: integer
      paymentGroupNumber:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentInvoiceAllocation:
    type: PaymentAllocation
    properties:
      paymentInvoiceAllocationName?:
        type: string
      appliedAmount:
        type: integer
      invoiceBalanceAmount:
        type: integer
      # Accelerators: added string union for PaymentInvoiceApplication.id reference
      paymentInvoiceApplication?:
        items: string | PaymentInvoiceApplication
  PaymentInvoiceApplication:
    type: PaymentApplication
    properties:
      paymentInvoiceApplicationName?:
        type: string
      invoiceBalanceAmount:
        type: integer
      paymentInvoiceApplicationType?:
        type: string
  PaymentPolicy:
    properties:
      id:
        type: string | nil
      name:
        type: string
      description:
        type: string
      # Accelerators: made property optional
      paymentPolicyTreatmentSelection?:
        type: string
      paymentPolicyStatus:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentTreatment:
    properties:
      id:
        type: string | nil
      # Accelerators: added string union for PaymentTreatmentMethod.id reference
      # Accelerators: made property optional
      paymentTreatmentMethod?:
        items: string | PaymentTreatmentMethod
      paymentApplicationLevel?:
        type: string
      shouldAutoInvoice?:
        type: boolean | nil
      paymentTreatmentStatus:
        type: string
      # Accelerators: added string union for PaymentPolicy.id reference
      # Accelerators: made property optional
      paymentPolicy?:
        items: string | PaymentPolicy
      paymentTreatmentName?:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  PaymentTreatmentMethod:
    properties:
      id:
        type: string | nil
      paymentTreatmentMethodName:
        type: string
      paymentTreatmentMethodCode:
        type: string
      paymentTreatmentMethodDescription:
        type: string
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  RefundAllocation:
    properties:
      id:
        type: string | nil
      effectiveDate:
        type: date-only
      # Accelerators: changed to string for RefundAllocation.id reference
      # Accelerators: made property optional
      relatedRefundAllocation?:
        items: string
      hasBeenUnapplied?:
        type: boolean | nil
      refundAllocationType:
        type: string
      # Accelerators: added string union for Payment.id reference
      # Accelerators: made property optional
      refundPayment?:
        items: string | Payment
      allocatedAmount:
        type: integer
      # Accelerators: made property optional
      refundBalanceAmount?:
        type: integer | nil
      refundAllocationName?:
        type: string
      appliedDate:
        type: date-only
      # Accelerators: made property optional
      externalCreatedDate?:
        type: date-only | nil
      # Accelerators: made property optional
      unappliedDate?:
        type: date-only | nil
      # Accelerators: added audit info block
      auditInfo?: GlobalTypes.AuditInfo
  RefundCreditMemoAllocation:
    type: RefundAllocation
    properties:
      name?:
        type: string
  RefundPayment:
    type: Payment
    properties:
      # Accelerators: made property optional
      externalCreatedDate?:
        type: date-only | nil
  RefundPaymentAllocation:
    type: RefundAllocation
    properties:
      # Accelerators: added string union for CapturePayment.id reference
      # Accelerators: made property optional
      capturePayment?:
        items: string | CapturePayment
      # Accelerators: made property optional
      refundAllocationCommentsDate?:
        type: date-only | nil
      # Accelerators: made property optional
      paymentBalanceAmount?:
        type: integer | nil
      refundAllocationCommentText?:
        type: string
      # Accelerators: made property optional
      creditMemoBalanceAmount?:
        type: integer | nil
      refundPaymentAllocationName?:
        type: string
