#%RAML 1.0 Trait
  responses:
      400:
        description:
          The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
        body:
          application/json:
            example: !include examples/returns-400-example.raml
      401:
        description:
          The supplied credentials are invalid.
        body:
          application/json:
            example: !include examples/returns-401-example.raml
      403:
        description:
          There is a problem with the credentials that were provided.
      404:
        description:
          The server cannot find the requested resource.
        body:
          application/json:
            example: !include examples/returns-404-example.raml
      405:
        description:
          A request was made of a resource using a request method not supported by that resource; for example, using GET on a form which requires data to be presented via POST, or using PUT on a read-only resource.
        body:
          application/json: 
            example: !include examples/returns-405-example.raml
      406:
        description:
          The target resource does not have a current representation that would be acceptable to the user agent.
        body:
          application/json:
            example: !include examples/returns-406-example.raml
      415:
        description:
          The accept header specified an unsupported media type.
        body:
          application/json: 
            example: !include examples/returns-415-example.raml
      500:
        description:
          An internal processing error occurred while processing the API request.
        body:
          application/json:
            example: !include examples/returns-500-example.raml
      597:
        description:
          Experience API timeout during dependent service invocation.
        body:
          application/json:
      598:
        description:
          Process API timeout during dependent service invocation.
        body:
          application/json:
      599:
        description:
          System API timeout during dependent service invocation.
        body:
          application/json: