#%RAML 1.0 Trait
usage: Apply this to any method that needs to be secured
description: Some requests require authentication
headers:
  authorization:
    description: Bearer Access Token Updated By Surya New Updated 444
    example: Bearer 5757gh76
    required: true
responses:
  401:
    description: Authorization failed