#%RAML 1.0 Trait
usage: Apply this to any method that needs interaction with vcs
description: Provides user information that the client already has, to avoid requesting this to CS. Should be temporary until performance is better.

headers:
  x-owner-id:
    description: |
     User's ownerId, which identifies the user performing the operation. 11111111
     This is NOT the username, but an UUID that can be found in the users page by the organization administrator.
    type: !include ../types/uuid.raml
  x-organization-id:
    description: |
      OrganizationId, which identifies the organization to which perform the operation. 
      This can be found in the organizations page by the organization administrator. Hello
    type: !include ../types/uuid.raml