#%RAML 1.0 Library
usage: This library provides extended types for the Party group

uses:
  FinanceTypes: ../exchange_modules/org.mule.examples/accelerator-cim-finance-library/1.2.0/accelerator-cim-finance-library.raml
  MarketTypes: ../exchange_modules/org.mule.examples/accelerator-cim-market-library/1.2.0/accelerator-cim-market-library.raml
  SellTypes: ../exchange_modules/org.mule.examples/accelerator-cim-sell-library/1.2.0/accelerator-cim-sell-library.raml
  GlobalTypes: ../exchange_modules/org.mule.examples/accelerator-cim-global-library/1.1.2/accelerator-cim-global-library.raml

types:
  AccountExt:
    type: MarketTypes.Account
    properties:
      autoPaymentMethodExt?: FinanceTypes.PaymentMethod[]
      orderDeliveryMethodExt?: SellTypes.OrderDeliveryMethod[]
