#%RAML 1.0 Library
usage: Provides CIM types defined in the Fulfill subject area

uses:
  ShipmentTypes: libraries/ShipmentTypeLibrary.raml

types:
  # Exported ShipmentTypes
  Shipment:
    type: ShipmentTypes.Shipment
    example: !include ./examples/ShipmentExample.json
  ShipmentDocument:
    type: ShipmentTypes.ShipmentDocument
    example: !include ./examples/ShipmentDocumentExample.json
  ShipmentPackage:
    type: ShipmentTypes.ShipmentPackage
    example: !include ./examples/ShipmentPackageExample.json
  ShipmentProduct:
    type: ShipmentTypes.ShipmentProduct
    example: !include ./examples/ShipmentProductExample.json
  ShipmentProductPriceAdjustment:
    type: ShipmentTypes.ShipmentProductPriceAdjustment
    example: !include ./examples/ShipmentProductPriceAdjustmentExample.json
  ShipmentProductPriceAdjustmentTax:
    type: ShipmentTypes.ShipmentProductPriceAdjustmentTax
    example: !include ./examples/ShipmentProductPriceAdjustmentTaxExample.json
  ShipmentStatus:
    type: ShipmentTypes.ShipmentStatus
    example: !include ./examples/ShipmentStatusExample.json
  ShippingMethod:
    type: ShipmentTypes.ShippingMethod
    example: !include ./examples/ShippingMethodExample.json
