#%RAML 1.0 Library
usage: Extensions to the CIM Sell subject area types

uses:
  ContractExtTypes: libraries/ContractExtTypeLibrary.raml
  PriceBookExtTypes: libraries/PriceBookExtTypeLibrary.raml
  SalesOrderExtTypes: libraries/SalesOrderExtTypeLibrary.raml

types:
  # Extended Contract types

  # Extended PriceBook types
  PriceBookEntryExt:
    type: PriceBookExtTypes.PriceBookEntryExt
    example: !include ./examples/PriceBookEntryExtExample.json

  # Extended SalesOrder types
  OrderDeliveryMethodExt:
    type: SalesOrderExtTypes.OrderDeliveryMethodExt
    example: !include ./examples/OrderDeliveryMethodExtExample.json
  SalesOrderExt:
    type: SalesOrderExtTypes.SalesOrderExt
    example: !include ./examples/SalesOrderExtExample.json
  SalesOrderDeliveryGroupExt:
    type: SalesOrderExtTypes.SalesOrderDeliveryGroupExt
    example: !include ./examples/SalesOrderDeliveryGroupExtExample.json
  SalesOrderPaymentSummaryExt:
    type: SalesOrderExtTypes.SalesOrderPaymentSummaryExt
    example: !include ./examples/SalesOrderPaymentSummaryExtExample.json
  SalesOrderProductExt:
    type: SalesOrderExtTypes.SalesOrderProductExt
    example: !include ./examples/SalesOrderProductExtExample.json
